name: release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "The type of the release."
        default: "patch"
        required: false

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - uses: actions/checkout@v2
        with:
          repository: "bakdata/ci-templates"
          path: "ci-templates"
      
      - name: Release charts
        uses: ./ci-templates/helm-release
        with:
          githubToken: "${{ secrets.GH_TOKEN }}"
          githubUsername: "${{ secrets.GH_USERNAME }}"
          githubEmail: "${{ secrets.GH_EMAIL }}"
          releaseType: "${{ github.event.inputs.releaseType }}"
          chartDirectory: "."
